# Site settings
title: LuoHuifen
email: 358186504@qq.com
description: "LuoHuifen's blog"
logo_location: "https://placeholdit.imgix.net/~text?txtsize=30&bg=F8F8F8&txtclr=002E62&txt=LOGO&w=100&h=100"

#baseurl: "" # the subpath of your site, e.g. /blog/
#url: "" # the base hostname & protocol for your site
# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: "https://LuoHuifen.github.io"

# The port used for local hosting
port: 3333
# Build settings
markdown: kramdown
kramdown:
  input: GFM

highlighter: pygments

#Other Global Configuration
exclude: ['README.md']

excerpt_separator: <!--more-->

#show the jumbotron header on index page
show_blog_header: true